### ISSUE TITLE
Get it working on macOS

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/steam.mod#2]
Initial work was done on Win32. There may be some things to do to get it working on macOS.

**Comment by GWRon** [comment]
Syntaxbomb-user Oddball made it compile by simply adding a further conditional:

> So I had a search around the modules source, I'm not really that well up on dynamic linked libraries in BlitzMax, but I've finally got it working. Had to add a couple of lines of code to steam.mod/steamsdk.mod/common.bmx

> I changed:
```BlitzMax
?win32x64
Import "-l:steam_api64.dll"
?linuxx64
Import "-lsteam_api"
?
```

> To this:
```BlitzMax
?win32x64
Import "-l:steam_api64.dll"
?macosx64
Import "-lsteam_api"
?linuxx64
Import "-lsteam_api"
?
```
> For the next person who comes along with the same issue.

https://www.syntaxbomb.com/index.php/topic,7926.msg347043552.html#msg347043552

**Comment by GWRon** [comment]
He further appended:

> Ok I've got it running how I want on Linux too now. So just for the purposes of completeness, and to help anyone who comes along afterwards with the same issue, here's the solution.

> On Linux libsteam_api.so should be install into the shared library folder on the users machine by Steam, but a lot of users are finding that's not the case. That's a Steam issue, but they do recommend shipping libsteam_api.so with your game anyway. BlitzMax NG created apps don't look in the local folder for shared libraries on Linux so some users are getting a crash.

> To get the steam module, or any other module, to look in the local folder for shared libraries add the following ModuleInfo line.

```Blitzmax
ModuleInfo "LD_OPTS: -Wl,-rpath,'$ORIGIN'"
```

> So in the steamsdk.bmx file you get

```Blitzmax
ModuleInfo "CPP_OPTS: -std=c++11"
?win32x64
ModuleInfo "LD_OPTS: -L%PWD%/sdk/redistributable_bin/win64"
?linuxx64
ModuleInfo "LD_OPTS: -L%PWD%/sdk/redistributable_bin/linux64"
ModuleInfo "LD_OPTS: -Wl,-rpath,'$ORIGIN'"
?macosx64
ModuleInfo "LD_OPTS: -L%PWD%/sdk/redistributable_bin/osx32"
?
```
> You can replace '$ORIGIN' with a relative path if you don't want to put the library in the apps root folder eg. './libs'
